import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Filter, Flag, Folder, Inbox, Menu, MoreHorizontal, Plus, Search, Settings, Sparkles, Tag, Target, Trash2, X, SlidersHorizontal, RefreshCw, Headphones, Paperclip, Pin, CheckCircle2, Repeat2 } from 'lucide-react';
import CloudShell from './CloudShell';
import { requestReminderPermission } from './backend/reminderScheduler';
import { createSubtask, deleteSubtask, loadSubtasks, updateSubtask } from './backend/subtaskRepository';
import './styles.css';
import './history.css';
import './next7.css';

const nowIso = () => new Date().toISOString();
const pad = n => String(n).padStart(2, '0');
const dateKey = d => `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
const startOfDay = d => new Date(d.getFullYear(), d.getMonth(), d.getDate());
const addDays = (d, n) => { const x = new Date(d); x.setDate(x.getDate() + n); return x; };
const prettyDay = d => new Intl.DateTimeFormat('en-US', { weekday: 'long' }).format(d);
const shortDay = d => new Intl.DateTimeFormat('en-US', { weekday: 'short' }).format(d);
const initialTasks = [
  { id: 1, title: 'To-do app completion', date: 'today', time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false },
  { id: 2, title: 'check all the projects to be deployed', date: 'today', time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false },
  { id: 3, title: 'New System design now', date: 'today', time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false },
  { id: 4, title: 'Yesterdays System Design', date: 'today', time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false },
  { id: 5, title: 'Finish resume updates', date: 'today', time: '4:00 PM', list: 'Personal', tag: 'Work', priority: 'high', pinned: true, done: false },
  { id: 6, title: 'Review tomorrow interview plan', date: 'tomorrow', time: '9:00 AM', list: 'Personal', tag: '', priority: 'medium', pinned: false, done: false },
  { id: 7, title: 'Buy groceries', date: 'upcoming', time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false }
].map(t => ({ ...t, createdAt: nowIso(), updatedAt: nowIso(), completedAt: null, notes: '' }));
const lists = ['Personal', 'Work'];
const tags = ['Important', 'Work', 'Personal', 'Health'];
const navItems = [['myday', 'My day', Target], ['next7', 'Next 7 days', CalendarDays], ['all', 'All my tasks', Inbox], ['calendar', 'My Calendar', CalendarDays]];
const historyDateKey = v => { const d = new Date(v); return Number.isNaN(d.getTime()) ? 'unknown' : d.toISOString().slice(0, 10); };
const historyDateLabel = v => v === 'unknown' ? 'Unknown date' : new Intl.DateTimeFormat('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' }).format(new Date(`${v}T12:00:00`));
function normalizeTask(t, i = 0) {
  const createdAt = t.createdAt || new Date(Date.now() - i * 60000).toISOString();
  return { ...t, id: t.id ?? `${Date.now()}-${i}`, title: t.title || 'Untitled task', date: t.date || 'upcoming', time: t.time || '', list: t.list || 'Personal', tag: t.tag || '', priority: t.priority || 'none', pinned: !!t.pinned, done: !!t.done, notes: t.notes || '', createdAt, updatedAt: t.updatedAt || createdAt, completedAt: t.completedAt || null, reminderAt: t.reminderAt || null, recurrenceRule: t.recurrenceRule || '' };
}
function taskDateKey(task, today = startOfDay(new Date())) {
  if (task.dueAt) { const d = new Date(task.dueAt); if (!Number.isNaN(d.getTime())) return dateKey(d); }
  if (/^\d{4}-\d{2}-\d{2}$/.test(task.date || '')) return task.date;
  if (task.date === 'today') return dateKey(today);
  if (task.date === 'tomorrow') return dateKey(addDays(today, 1));
  return null;
}

function App() {
  const [tasks, setTasks] = useState(() => { try { const s = JSON.parse(localStorage.getItem('anyday.tasks') || 'null'); return Array.isArray(s) ? s.map(normalizeTask) : initialTasks; } catch { return initialTasks; } });
  const [view, setView] = useState('myday');
  const [selected, setSelected] = useState(null);
  const [query, setQuery] = useState('');
  const [newTask, setNewTask] = useState('');
  const [suggestions, setSuggestions] = useState(true);
  const [settings, setSettings] = useState(false);
  const [notice, setNotice] = useState(true);
  const [dark, setDark] = useState(true);
  const [mobileNav, setMobileNav] = useState(false);
  const [showFilters, setShowFilters] = useState(false);
  const [filter, setFilter] = useState('all');
  const [historyStatus, setHistoryStatus] = useState('all');
  const [historyRange, setHistoryRange] = useState('all');
  useEffect(() => { localStorage.setItem('anyday.tasks', JSON.stringify(tasks)); window.dispatchEvent(new Event('anyday:local-change')); }, [tasks]);
  useEffect(() => { const sync = () => { try { const s = JSON.parse(localStorage.getItem('anyday.tasks') || 'null'); if (Array.isArray(s)) setTasks(s.map(normalizeTask)); } catch {} }; window.addEventListener('anyday:remote-change', sync); return () => window.removeEventListener('anyday:remote-change', sync); }, []);
  const matches = useMemo(() => tasks.filter(t => (!query || t.title.toLowerCase().includes(query.toLowerCase())) && (filter === 'all' || t.priority === filter)), [tasks, query, filter]);
  const today = startOfDay(new Date());
  const active = matches.filter(t => !t.done);
  const allTasks = matches;
  const myDay = active.filter(t => taskDateKey(t, today) === dateKey(today));
  const selectedTask = tasks.find(t => t.id === selected) || null;
  const addTask = (e, forcedDate = null) => {
    e?.preventDefault(); if (!newTask.trim()) return;
    const d = forcedDate || (view === 'myday' ? today : addDays(today, 1)); const ts = nowIso();
    const task = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, title: newTask.trim(), date: dateKey(d), time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false, notes: '', createdAt: ts, updatedAt: ts, completedAt: null };
    setTasks(v => [task, ...v]); setNewTask(''); setSelected(task.id);
  };
  const addTaskForDate = (title, d) => {
    if (!title.trim()) return; const ts = nowIso();
    const task = { id: `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, title: title.trim(), date: dateKey(d), time: '', list: 'Personal', tag: '', priority: 'none', pinned: false, done: false, notes: '', createdAt: ts, updatedAt: ts, completedAt: null };
    setTasks(v => [task, ...v]);
  };
  const updateTask = (id, patch) => setTasks(v => v.map(t => t.id === id ? { ...t, ...patch, updatedAt: nowIso() } : t));
  const toggleTask = id => setTasks(v => v.map(t => { if (t.id !== id) return t; const done = !t.done, ts = nowIso(); return { ...t, done, completedAt: done ? ts : null, updatedAt: ts }; }));
  const deleteTask = id => { setTasks(v => v.filter(t => t.id !== id)); setSelected(null); };
  return <div className={dark ? 'app dark' : 'app'}>
    {notice && <div className="permission-banner">AnyDay needs your permission to <u>enable reminder and calendar notifications</u><button onClick={() => setNotice(false)}><X size={20} /></button></div>}
    <aside className={mobileNav ? 'sidebar mobile-open' : 'sidebar'}><div className="account"><div className="gear-circle"><Settings size={22} /></div><div><strong>Sree</strong><span>All features enabled</span></div></div><button className="primary-add" onClick={() => document.querySelector('.quick-add input')?.focus()}><Plus size={18} /> Add task</button><div className="side-scroll"><div className="nav-group">{navItems.map(([id, label, Icon]) => <button key={id} className={view === id ? 'nav active' : 'nav'} onClick={() => { setView(id); setMobileNav(false); }}><Icon size={19} /><span>{label}</span>{id === 'myday' && <em>{myDay.length}</em>}{id === 'next7' && <em>{active.filter(t => { const k = taskDateKey(t, today); return k && k >= dateKey(today) && k <= dateKey(addDays(today, 6)); }).length}</em>}{id === 'all' && <em>{allTasks.length}</em>}</button>)}</div><div className="side-heading"><span>My lists</span><button><Plus size={19} /></button></div>{lists.map((x, i) => <button className="nav list-nav" key={x} onClick={() => setView('list:' + x)}><span className={'list-dot dot-' + i}></span><span>{x}</span><em>{tasks.filter(t => t.list === x && !t.done).length}</em></button>)}<div className="side-heading"><span>Tags</span><button><Plus size={19} /></button></div>{tags.map(x => <button className="nav tag-nav" key={x} onClick={() => setView('tag:' + x)}><Tag size={15} /><span>{x}</span></button>)}</div><div className="side-bottom"><button className="nav"><CircleHelp size={19} /> Help & feedback</button><button className="nav" onClick={() => setSettings(true)}><Settings size={19} /> Settings</button></div></aside>
    <main className="workspace"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileNav(v => !v)}><Menu size={22} /></button><div className="brand-small">AnyDay</div><div className="top-icons"><div className="global-search"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tasks" /></div><button title="Sync"><RefreshCw size={19} /></button><button title="Help"><Headphones size={20} /></button><button className="notify" title="Notifications"><Inbox size={20} /><i></i></button><button onClick={() => setDark(v => !v)} title="Theme">◐</button></div></header>
      <div className="main-grid"><section className="day-panel">{view === 'myday' ? <><div className="hero-copy"><h1>Good Afternoon, Sree<span>.</span></h1><h2>You are what you do</h2></div><div className="calendar-connect"><div className="date-block"><b>{shortDay(today).toUpperCase()}</b><strong>{today.getDate()}</strong><span>{new Intl.DateTimeFormat('en-US', { month: 'long' }).format(today)}</span></div><div className="connect-copy"><strong>Join video meetings with one tap</strong><div><button>📅 Connect Google Calendar</button><button>▣ Connect Outlook Calendar</button><button>☁ Connect iCloud Calendar</button></div></div></div><TaskList tasks={myDay} toggleTask={toggleTask} selectTask={setSelected} /><QuickAdd addTask={addTask} newTask={newTask} setNewTask={setNewTask} /></> : view === 'next7' ? <Next7View tasks={matches} toggleTask={toggleTask} selectTask={setSelected} addTaskForDate={addTaskForDate} showFilters={showFilters} setShowFilters={setShowFilters} filter={filter} setFilter={setFilter} /> : view === 'calendar' ? <Calendar tasks={tasks} /> : <GenericView view={view} tasks={view === 'all' ? allTasks : view.startsWith('list:') ? active.filter(t => t.list === view.slice(5)) : view.startsWith('tag:') ? active.filter(t => t.tag === view.slice(4)) : active} allTasks={allTasks} toggleTask={toggleTask} selectTask={setSelected} addTask={addTask} newTask={newTask} setNewTask={setNewTask} historyStatus={historyStatus} setHistoryStatus={setHistoryStatus} historyRange={historyRange} setHistoryRange={setHistoryRange} />}</section>
        <aside className="right-panel"><div className="right-tools"><button className="suggestions-title" onClick={() => setSuggestions(v => !v)}><Sparkles size={19} /> Suggestions</button><button onClick={() => setShowFilters(v => !v)}><FilterIcon /></button><button onClick={() => setSettings(true)}><Settings size={19} /></button></div><div className="filter-row"><span>Filter</span><button onClick={() => setShowFilters(v => !v)}><SlidersHorizontal size={17} /></button></div>{showFilters && <div className="filter-menu"><button onClick={() => setFilter('all')}>All priorities</button><button onClick={() => setFilter('high')}>High priority</button><button onClick={() => setFilter('medium')}>Medium priority</button></div>}{suggestions && <div className="suggestion-stack"><Suggestion title="Watch My day tutorial" meta="From 0 days ago" add={() => {}} /><Suggestion title="Add me to My Day" meta="Recently active" add={() => {}} /></div>}<div className="tutorial-card"><div className="fake-video"><div className="play">▶</div></div><strong>Tap to learn about My day</strong></div></aside></div></main>
    {selectedTask && <TaskDetail task={selectedTask} updateTask={updateTask} deleteTask={deleteTask} close={() => setSelected(null)} />}{settings && <SettingsModal close={() => setSettings(false)} dark={dark} setDark={setDark} />}</div>;
}

function QuickAdd({ addTask, newTask, setNewTask }) { return <form className="quick-add" onSubmit={addTask}><Plus size={20} /><input value={newTask} onChange={e => setNewTask(e.target.value)} placeholder="Enter task title" /><button type="submit"><span className="arrow-up">↑</span></button></form>; }
function FilterIcon() { return <span className="filter-lines">≡</span>; }
function TaskList({ tasks, toggleTask, selectTask }) { return <div className="task-list">{tasks.length ? tasks.map(t => <TaskRow key={t.id} task={t} toggleTask={toggleTask} selectTask={selectTask} />) : <div className="empty-state">Your day is clear. Add a task below.</div>}</div>; }
function TaskRow({ task, toggleTask, selectTask }) { return <div className={'task-row ' + (task.pinned ? 'pinned ' : '') + (task.done ? 'completed' : '')} onClick={() => selectTask(task.id)}><button className="circle-check" onClick={e => { e.stopPropagation(); toggleTask(task.id); }}>{task.done && <Check size={14} />}</button><div className="task-text"><div>{task.title}</div>{(task.time || task.tag || task.priority !== 'none') && <small>{task.time}{task.tag && ` · ${task.tag}`}{task.priority !== 'none' && ` · ${task.priority}`}</small>}</div><div className="task-end">{task.pinned && <Pin size={13} />}<MoreHorizontal size={20} /></div></div>; }
function Suggestion({ title, meta, add }) { return <div className="suggestion-card"><button className="plus-suggest" onClick={add}><Plus size={19} /></button><div><div className="suggestion-source">⌑ My lists &gt; Personal</div><strong>{title}</strong><small>{meta}</small></div></div>; }

function Next7View({ tasks, toggleTask, selectTask, addTaskForDate, showFilters, setShowFilters, filter, setFilter }) {
  const [anchor, setAnchor] = useState(startOfDay(new Date()));
  const [status, setStatus] = useState('active');
  const days = Array.from({ length: 7 }, (_, i) => addDays(anchor, i));
  const keys = new Set(days.map(dateKey));
  const visible = tasks.filter(t => { const k = taskDateKey(t, anchor); if (!k || !keys.has(k)) return false; if (status === 'active' && t.done) return false; if (status === 'completed' && !t.done) return false; return true; });
  const clearCompleted = () => visible.filter(t => t.done).forEach(t => toggleTask(t.id));
  return <div className="next7-view">
    <div className="next7-toolbar"><div className="next7-title-pill"><CalendarDays size={22} /><strong>Next 7 days</strong></div><div className="next7-toolbar-actions"><button className="next7-filter-button" onClick={() => setShowFilters(v => !v)}><SlidersHorizontal size={18} /> Filter</button><button className="next7-more" aria-label="More options"><MoreHorizontal size={20} /></button><button className="clear-completed" onClick={clearCompleted}><CheckCircle2 size={17} /> Clear completed</button></div></div>
    {showFilters && <div className="next7-filter-popover"><div><span>Status</span><button className={status === 'active' ? 'selected' : ''} onClick={() => setStatus('active')}>Active</button><button className={status === 'all' ? 'selected' : ''} onClick={() => setStatus('all')}>All</button><button className={status === 'completed' ? 'selected' : ''} onClick={() => setStatus('completed')}>Completed</button></div><div><span>Priority</span><button className={filter === 'all' ? 'selected' : ''} onClick={() => setFilter('all')}>All</button><button className={filter === 'high' ? 'selected' : ''} onClick={() => setFilter('high')}>High</button><button className={filter === 'medium' ? 'selected' : ''} onClick={() => setFilter('medium')}>Medium</button></div></div>}
    <div className="next7-scroller"><div className="next7-board">{days.map((d, i) => { const key = dateKey(d); const dayTasks = visible.filter(t => taskDateKey(t, anchor) === key).sort((a, b) => Number(b.pinned) - Number(a.pinned) || new Date(a.createdAt) - new Date(b.createdAt)); const isToday = key === dateKey(startOfDay(new Date())); const label = i === 0 && isToday ? 'Today' : i === 1 && key === dateKey(addDays(startOfDay(new Date()), 1)) ? 'Tomorrow' : prettyDay(d); return <section className={'next7-day-card ' + (isToday ? 'is-today' : '')} key={key}><header><div><strong>{label}</strong><span>{shortDay(d)}</span></div><small>{new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric' }).format(d)}</small></header><div className="next7-task-stack">{dayTasks.map(t => <Next7Task key={t.id} task={t} toggleTask={toggleTask} selectTask={selectTask} />)}{!dayTasks.length && <div className="next7-empty">No tasks</div>}</div><InlineAdd date={d} onAdd={addTaskForDate} /></section>; })}</div></div>
    <div className="next7-footer"><button onClick={() => setAnchor(addDays(anchor, -7))}><ChevronLeft size={17} /> Previous 7 days</button><button className="next7-today" onClick={() => setAnchor(startOfDay(new Date()))}>Today</button><span>{visible.length} task{visible.length === 1 ? '' : 's'} shown</span><button onClick={() => setAnchor(addDays(anchor, 7))}>Next 7 days <ChevronRight size={17} /></button></div>
  </div>;
}
function Next7Task({ task, toggleTask, selectTask }) { return <article className={'next7-task ' + (task.done ? 'done' : '')} onClick={() => selectTask(task.id)}><button className="next7-check" onClick={e => { e.stopPropagation(); toggleTask(task.id); }}>{task.done && <Check size={13} />}</button><div className="next7-task-content"><div className="next7-source"><span>♙</span> My lists &gt; {task.list || 'Personal'}</div><strong>{task.title}</strong>{(task.time || task.tag || task.priority !== 'none') && <small>{task.time}{task.tag && ` · ${task.tag}`}{task.priority !== 'none' && ` · ${task.priority}`}</small>}</div>{task.pinned && <Pin size={14} className="next7-pin" />}</article>; }
function InlineAdd({ date, onAdd }) { const [value, setValue] = useState(''); const submit = e => { e.preventDefault(); if (!value.trim()) return; onAdd(value, date); setValue(''); }; return <form className="next7-inline-add" onSubmit={submit}><Plus size={18} /><input value={value} onChange={e => setValue(e.target.value)} placeholder="Add Task" /></form>; }

function GenericView({ view, tasks, allTasks, toggleTask, selectTask, addTask, newTask, setNewTask, historyStatus, setHistoryStatus, historyRange, setHistoryRange }) { const title = view === 'all' ? 'All my tasks' : view.startsWith('list:') ? view.slice(5) : view.startsWith('tag:') ? '#' + view.slice(4) : 'My tasks'; return <><div className="generic-head"><div><h1>{title}</h1><p>{view === 'all' ? `${allTasks.length} task${allTasks.length === 1 ? '' : 's'} stored in your complete history` : 'Plan, organize and get things done.'}</p></div><button onClick={() => setHistoryStatus(v => v === 'all' ? 'active' : 'all')}><Filter size={17} /></button></div>{view === 'all' ? <AllTasksHistory tasks={tasks} toggleTask={toggleTask} selectTask={selectTask} status={historyStatus} setStatus={setHistoryStatus} range={historyRange} setRange={setHistoryRange} /> : <TaskList tasks={tasks} toggleTask={toggleTask} selectTask={selectTask} />}<QuickAdd addTask={addTask} newTask={newTask} setNewTask={setNewTask} /></>; }
function AllTasksHistory({ tasks, toggleTask, selectTask, status, setStatus, range, setRange }) { const today = startOfDay(new Date()), filtered = tasks.filter(t => { if (status === 'active' && t.done) return false; if (status === 'completed' && !t.done) return false; if (range !== 'all') { const days = range === '7' ? 7 : range === '30' ? 30 : 365, cutoff = new Date(today); cutoff.setDate(cutoff.getDate() - days + 1); if (new Date(t.createdAt) < cutoff) return false; } return true; }), grouped = filtered.reduce((a, t) => { const k = historyDateKey(t.createdAt || t.updatedAt); (a[k] || []).push(t); return a; }, {}), groups = Object.entries(grouped).sort(([a], [b]) => b.localeCompare(a)); return <div className="all-history"><div className="history-summary"><span><CheckCircle2 size={16} /> All entered tasks</span><strong>{filtered.length}</strong><span className="history-done">{filtered.filter(t => t.done).length} completed</span></div><div className="history-controls"><div className="history-control-group"><button className={status === 'all' ? 'selected' : ''} onClick={() => setStatus('all')}>All</button><button className={status === 'active' ? 'selected' : ''} onClick={() => setStatus('active')}>Active</button><button className={status === 'completed' ? 'selected' : ''} onClick={() => setStatus('completed')}>Completed</button></div><select value={range} onChange={e => setRange(e.target.value)}><option value="all">All time</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="365">Last year</option></select></div>{!groups.length ? <div className="history-empty"><CheckCircle2 size={34} /><h3>No matching tasks</h3><p>Your complete history is preserved; adjust the filters to see older entries.</p></div> : groups.map(([k, ts]) => <section className="history-group" key={k}><div className="history-heading"><span>{historyDateLabel(k)}</span><em>{ts.length}</em></div>{ts.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)).map(t => <TaskRow key={t.id} task={t} toggleTask={toggleTask} selectTask={selectTask} />)}</section>)}</div>; }
function Calendar({ tasks }) { const d = new Date(); return <div className="calendar-view"><div className="generic-head"><div><h1>My Calendar</h1><p>See your tasks and events together.</p></div><div className="month-nav"><button><ChevronLeft size={17} /></button><strong>{d.toLocaleString('en-US', { month: 'long', year: 'numeric' })}</strong><button><ChevronRight size={17} /></button></div></div><div className="calendar-grid">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'].map(x => <div className="calendar-day-name" key={x}>{x}</div>)}{Array.from({ length: 35 }, (_, i) => <div className={'calendar-cell ' + (i === 18 ? 'today' : '')} key={i}><b>{i > 0 && i <= 30 ? i : ''}</b>{i === 18 && tasks.filter(t => t.date === 'today').slice(0, 2).map(t => <div className="calendar-task" key={t.id}>{t.title}</div>)}</div>)}</div></div>; }

function TaskDetail({ task, updateTask, deleteTask, close }) {
  const [note, setNote] = useState(task.notes || '');
  const [subtasks, setSubtasks] = useState([]);
  const [subTitle, setSubTitle] = useState('');
  const [files, setFiles] = useState([]);
  useEffect(() => { setNote(task.notes || ''); }, [task.id, task.notes]);
  useEffect(() => { let live = true; loadSubtasks(task.id).then(rows => { if (live) setSubtasks(rows); }).catch(() => {}); return () => { live = false; }; }, [task.id]);
  const localDate = task.dueAt ? new Date(task.dueAt) : null;
  const dateValue = localDate && !Number.isNaN(localDate.getTime()) ? dateKey(localDate) : /^\d{4}-\d{2}-\d{2}$/.test(task.date || '') ? task.date : task.date === 'tomorrow' ? dateKey(addDays(new Date(), 1)) : dateKey(new Date());
  const timeValue = localDate && !Number.isNaN(localDate.getTime()) ? pad(localDate.getHours()) + ':' + pad(localDate.getMinutes()) : '';
  const saveDue = (date, time = '') => { if (!date) return updateTask(task.id, { date: 'upcoming', dueAt: null, time: '' }); const d = new Date(date + 'T' + (time || '09:00') + ':00'); updateTask(task.id, { date, dueAt: d.toISOString(), time: time ? d.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : '' }); };
  const setReminder = value => { if (!value) return updateTask(task.id, { reminderAt: null }); requestReminderPermission().catch(() => {}); updateTask(task.id, { reminderAt: new Date(value).toISOString() }); };
  const addSub = async e => { e.preventDefault(); if (!subTitle.trim()) return; const temp = { id: 'local-' + Date.now(), task_id: task.id, title: subTitle.trim(), completed: false, position: subtasks.length }; setSubtasks(v => [...v, temp]); setSubTitle(''); try { const row = await createSubtask(task.id, temp.title); if (row) setSubtasks(v => v.map(x => x.id === temp.id ? row : x)); } catch {} };
  const toggleSub = async s => { const next = !s.completed; setSubtasks(v => v.map(x => x.id === s.id ? { ...x, completed: next } : x)); if (!String(s.id).startsWith('local-')) try { await updateSubtask(s.id, { completed: next }); } catch {} };
  const removeSub = async s => { setSubtasks(v => v.filter(x => x.id !== s.id)); if (!String(s.id).startsWith('local-')) try { await deleteSubtask(s.id); } catch {} };
  return <aside className="detail-panel"><div className="detail-top"><button onClick={close}><X size={17} /></button><div><button onClick={() => updateTask(task.id, { done: !task.done })}><Check size={15} /> {task.done ? 'Reopen' : 'Done'}</button><button onClick={() => updateTask(task.id, { pinned: !task.pinned })}><Pin size={15} /> {task.pinned ? 'Unpin' : 'Pin'}</button></div><button onClick={() => deleteTask(task.id)}><Trash2 size={17} /></button></div>
  <input className="detail-title" value={task.title} onChange={e => updateTask(task.id, { title: e.target.value })} />
  <DetailSection label="LIST"><select className="detail-select" value={task.list || 'Personal'} onChange={e => updateTask(task.id, { list: e.target.value, listId: null })}>{lists.map(x => <option key={x}>{x}</option>)}</select></DetailSection>
  <DetailSection label="DUE DATE"><div className="date-options"><input type="date" value={dateValue} onChange={e => saveDue(e.target.value, timeValue)} /><input type="time" value={timeValue} onChange={e => saveDue(dateValue, e.target.value)} /></div><div className="date-options" style={{ marginTop: 7 }}><button onClick={() => updateTask(task.id, { date: 'today', dueAt: null, time: '' })}>Today</button><button onClick={() => updateTask(task.id, { date: 'tomorrow', dueAt: null, time: '' })}>Tomorrow</button><button onClick={() => updateTask(task.id, { date: 'upcoming', dueAt: null, time: '' })}>No date</button></div></DetailSection>
  <DetailSection label="REMINDER"><div className="reminder-editor"><input type="datetime-local" value={task.reminderAt ? new Date(task.reminderAt).toISOString().slice(0,16) : ''} onChange={e => setReminder(e.target.value)} />{task.reminderAt && <button onClick={() => updateTask(task.id, { reminderAt: null })}>Clear</button>}</div></DetailSection>
  <DetailSection label="REPEAT"><div className="repeat-row"><Repeat2 size={15} /><select value={task.recurrenceRule || ''} onChange={e => updateTask(task.id, { recurrenceRule: e.target.value })}><option value="">Does not repeat</option><option value="daily">Every day</option><option value="weekly">Every week</option><option value="monthly">Every month</option></select></div></DetailSection>
  <DetailSection label="SUBTASKS"><form className="sub-add" onSubmit={addSub}><Plus size={15} /><input value={subTitle} onChange={e => setSubTitle(e.target.value)} placeholder="Add a subtask" /></form>{subtasks.map(s => <div className="sub-item" key={s.id}><button className="circle-check" onClick={() => toggleSub(s)}>{s.completed && <Check size={12} />}</button><span style={{ textDecoration: s.completed ? 'line-through' : 'none' }}>{s.title}</span><button onClick={() => removeSub(s)} style={{ marginLeft: 'auto', background: 'none', border: 0, color: '#777' }}><X size={13} /></button></div>)}</DetailSection>
  <DetailSection label="NOTES"><textarea value={note} onChange={e => setNote(e.target.value)} onBlur={() => updateTask(task.id, { notes: note })} placeholder="Add notes..." /></DetailSection>
  <DetailSection label="TAG"><select className="detail-select" value={task.tag || ''} onChange={e => updateTask(task.id, { tag: e.target.value })}><option value="">No tag</option>{tags.map(x => <option key={x}>{x}</option>)}</select></DetailSection>
  <DetailSection label="PRIORITY"><div className="date-options">{['none','low','medium','high'].map(p => <button key={p} className={task.priority === p ? 'chosen' : ''} onClick={() => updateTask(task.id, { priority: p })}><Flag size={13} /> {p}</button>)}</div></DetailSection>
  <DetailSection label="ATTACHMENTS"><input type="file" multiple onChange={e => setFiles(Array.from(e.target.files || []))} /><div className="attachment"><Paperclip size={14} />{files.length ? files.length + ' file' + (files.length === 1 ? '' : 's') + ' selected locally' : <>Drop files here or <b>browse</b></>}</div></DetailSection></aside>;
}function DetailSection({ label, children }) { return <div className="detail-section"><div className="detail-label">{label}</div>{children}</div>; }
function SettingsModal({ close, dark, setDark }) { return <div className="overlay" onMouseDown={close}><div className="settings-modal" onMouseDown={e => e.stopPropagation()}><div className="settings-head"><h2>Settings</h2><button onClick={close}><X size={18} /></button></div><div className="setting-row"><div><strong>Dark mode</strong><span>Use the dark AnyDay workspace.</span></div><button className="toggle" onClick={() => setDark(v => !v)}>{dark ? 'On' : 'Off'}</button></div><div className="setting-row"><div><strong>Complete task history</strong><span>AnyDay keeps tasks entered on previous days.</span></div><span className="setting-value">Always on</span></div><div className="setting-row"><div><strong>Notifications</strong><span>Reminder and calendar notifications.</span></div><span className="setting-value">Enabled</span></div></div></div>; }

createRoot(document.getElementById('root')).render(<CloudShell><App /></CloudShell>);
